### ISSUE TITLE
Update tests that enable Minify JS/CSS as warning is removed from WPR UI since 3.16.3

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket-e2e#127]
Error will appear while running smoke tests as timeout to get the warning notice for Minify JS/CSS. This is removed from UI since WPR 3.16.3
![Screenshot from 2024-07-30 14-29-21](https://github.com/user-attachments/assets/25d3b545-c8bb-4a5d-bea2-8456b926cdbd)

**Comment by MathieuLamiot** [comment]
**How to reproduce the issue**
Run smoke tests (`npm run test:smoke`) on WP Rocket 3.16.3 or above. The 2 errors will appear, as in above screenshot.

**Root cause of the issue**
For both the Minify CSS and Minify JS options, there is no additional pop-up anymore after ticking the option to validate its activation.
Currently, Rocket-E2E waits for this pop-up to show up and tries to interact with it because of the lines:

```
                after: async (page: Page, state: boolean): Promise<void> => {
                     await activateFromPopUp(page, state, "text=Activate minify CSS") 
                }
```

and 

```
                after: async (page: Page, state: boolean): Promise<void> => {
                    await activateFromPopUp(page, state, "text=Activate minify JavaScript") 
               }
```
Those "after" actions are triggered from the `toggle` method (see at the end of it:

```
            if (this.propertyExist(optionId, "after")) {
                await this.elements[optionId].after(this.page, this.optionState);
            }
```

**Scope a solution**

We can simply remove the `after`  property of elements `minify_css` and `minify_js` in `src/common/selector.ts`.

To confirm, run again the smoke tests.

Effort estimation: XS
Can be peer-coded: Yes
Is a refactor needed in that part of the codebase?
No
