### ISSUE TITLE
LRC visual regression on live templates

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket-e2e#137]
Scenario: Shouldn't cause visual regression when visiting x template
Given: 3.17+ is active
And: Visit x page
When: clear cache 
And: visit the page
then: no visual regression compared to nowprocket

Templates:
delayjs_1.3_live_template.php 
delayjs_68_live_template.php
page lcp_6647_live.php
lcp_live_4_template.php
lcp_live_test_span.php
rucss_5213_template.php
template 4787.php
lrc_will_site.php

**Comment by MathieuLamiot** [comment]
Looks like we might already have all the needed code, and we just need to put together test scenarios with list of files to test against?

See the step `I must not see any visual regression`

**Comment by jeawhanlee** [comment]
### Scope a solution ✅
- Add the new templates for VR testing to the SCENARIO_URLS in wp.config.ts
- Create a new feature with a new tag with steps to install new_release, visit page, clear cache and perform backstop reference comparison.

### Estimate the effort ✅
[S]

For Added context, we need to make some changes to the way we create references, as all urls in SCENARIO_URLS will be created as references which for most regression tests, we will not tests all references but rather just a few, take for example this current grooming, if we are to add the new templates to the SCENARIO_URLS we will have other templates there in the object that will not be tested for that test cycle simple because we don't need to.

I added an issue for this [here](https://github.com/wp-media/wp-rocket-e2e/issues/138) @MathieuLamiot

**Comment by MathieuLamiot** [comment]
Thanks @jeawhanlee. I added your issue to the cooldown board. Up to @wp-media/qa-team and you to decide what needs to be prioritized first among those E2E visual regression issues :)
