### ISSUE TITLE
Summarize Rocket-E2E results from Remote Desktop

### ISSUE THREAD

**Issue by MathieuLamiot** [wp-media/wp-rocket-e2e#165]
**Context**
We now have many test results from Rocket-E2E from Remote Destkop: https://wp-media.slack.com/archives/C05NH7JU4S2/p1729513024781269

**Expected outcome**

Create an excel (or google sheet) file with:
- One column per test in the test plan
- One line per test report
For each report/test, mark it as OK/KO.

From there, identify:
- Tests that are always passing
- Tests that are always failing
- Flaky tests

For failing/flaky tests, check if there is already a GH issue or create it. Then reference it in the Excel file.

Warning: Note that some fixes were applied between the first and last reports, so let's take that into account. For instance, tests failing in the first reports because of WP Rocket not being properly uninstalled should not be considerd flaky because they have been fixed in the meantime, etc.

**Comment by MathieuLamiot** [comment]
I created first obvious issues: #166 #167 #168

**Comment by Mai-Saad** [comment]
WIP: gathering data here https://docs.google.com/spreadsheets/d/1L9ZsL0kCaYg3ytqcnKikKsQDAfLNCiV6iC9_hgvYryE/edit?usp=sharing

**Comment by Mai-Saad** [comment]
> I created first obvious issues: https://github.com/wp-media/wp-rocket-e2e/issues/166 https://github.com/wp-media/wp-rocket-e2e/issues/167 https://github.com/wp-media/wp-rocket-e2e/issues/168

This too can be added to the list https://github.com/wp-media/wp-rocket-e2e/issues/172

**Comment by Mai-Saad** [comment]
We can add this too https://github.com/wp-media/wp-rocket-e2e/issues/173

**Comment by Mai-Saad** [comment]
Using the latest commit on dev 80bde4edadef9cc888af8c90e689bb8ca53283e5, the remaining failures are due to:
https://github.com/wp-media/wp-rocket-e2e/issues/166
https://github.com/wp-media/wp-rocket-e2e/issues/167

llimages for single colon and Scenario:C16388 - Should clear performance hints of the URL when edited  => probably related to this https://github.com/wp-media/wp-rocket-e2e/issues/173 as when active theme is 2020, all is green
