### ISSUE TITLE
Fix tests related to the CPCSS notice

### ISSUE THREAD

**Issue by MathieuLamiot** [wp-media/wp-rocket-e2e#166]
See Rocket-E2E test results shared by the team.

**Comment by jeawhanlee** [comment]
### Reproduce the problem ✅
I was able to reproduce the problem by running `npm run test:e2e`

### Identify the root cause ✅
- Firstly, the selector configuration [here](https://github.com/wp-media/wp-rocket-e2e/blob/83ed6a7e69578951459f70dc58e47b4174d06897/src/common/selectors.ts#L65-L75) is wrong
- We are not using `async` & `await` on this [step](https://github.com/wp-media/wp-rocket-e2e/blob/e43c0ea4fab6c17ef930ba8f7f46f5ddf94a1078/src/support/steps/steps.ts#L86-L88)
- We don't have a proper cleanup on this test as well

### Scope a solution ✅
- In https://github.com/wp-media/wp-rocket-e2e/blob/83ed6a7e69578951459f70dc58e47b4174d06897/src/common/selectors.ts
  - We need to update this [lines](https://github.com/wp-media/wp-rocket-e2e/blob/83ed6a7e69578951459f70dc58e47b4174d06897/src/common/selectors.ts#L66-L74) to something like this:
  ```
   cpcss:{
      type: FieldType.checkbox,
      element: "#optimize_css_delivery",
      target: "label[for=optimize_css_delivery]",
      after: async (page: Page): Promise<void> => {
          await page.locator("#wpr-radio-async_css").click();
      },
  },
  ```
  On the `after` call back, we need to bail out when the option is enabled.

- In https://github.com/wp-media/wp-rocket-e2e/blob/e43c0ea4fab6c17ef930ba8f7f46f5ddf94a1078/src/support/steps/steps.ts
  - Update [step](https://github.com/wp-media/wp-rocket-e2e/blob/e43c0ea4fab6c17ef930ba8f7f46f5ddf94a1078/src/support/steps/steps.ts#L86-L88) to use `async` & `await`
  
- In https://github.com/wp-media/wp-rocket-e2e/blob/0bfa67601fa427e72d86628187eb8061187f23cc/src/features/notice.feature
  - Add `@setup` tag to the feature.

### Estimate the effort ✅
[S]
