### ISSUE TITLE
Tests for Check if content are lazyloaded while scrolling seems always failing for the templates lazyload_css_background_images, ll_bg_css_single_colon and ll_bg_css_double_colon

### ISSUE THREAD

**Issue by MathieuLamiot** [wp-media/wp-rocket-e2e#168]

**Comment by jeawhanlee** [comment]
### Reproduce the problem ✅
I was able to reproduce the problem by activating WPML and running only `npm run test:llimages`

### Identify the root cause ✅
The test is failing for 2 reasons
- WPML is active and it captures its flags images in this array [here](https://github.com/wp-media/wp-rocket-e2e/blob/3a6f9e1232bf00f34ad5a720dbd2799ad8f8aa18/src/support/steps/ll-css-bg-image.ts#L149)
- We are asserting that the array [here](https://github.com/wp-media/wp-rocket-e2e/blob/3a6f9e1232bf00f34ad5a720dbd2799ad8f8aa18/src/support/steps/ll-css-bg-image.ts#L183) must be the same which is not the case for scenario 2 and 3

### Scope a solution ✅
- Check if WPML is activated and deactivate before running the related test.
- Secondly, Assert instead that the images loaded are in the expected array.
   - `expect(images.every(image => LL_BACKGROUND_IMAGES[page].lazyLoadedImages.includes(image))).toBeTruthy();`

### Estimate the effort ✅
[XS]
