### ISSUE TITLE
As a test engineer, I'd like to run smoke/regression test for new Delay JS script using the tool

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket-e2e#42]
**Is your feature request related to a problem? Please describe.**
With every change at Delay JS script, we need to:
1- Ensure that no console error with different themes => scenario1
2- The mobile menu is working using a single click with different themes => scenario2
3- The links are clickable => scenario3
4- Ensure that no console error with different plugins => Scenario 4 and todo: gather other plugins to be checked based on issues history
5- Rerun some regression tests related to the script => Tests with e2e playwright automation type [here](https://wpmediaqa.testrail.io/index.php?/suites/view/1&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=4884)

**Describe the solution you'd like**
Scenario1: Shouldn't cause console error when enabling Delay JS with different themes
Given Delay JS is enabled
When theme 'x' is activated
And visit the home page 
And move the mouse 
Then no console error different than nowprocket page

Scenario2: Should the mobile menu work While Delay JS is enabled
Given Delay JS is enabled
And Separate mobile cache is enabled
When theme 'x' is activated
And visit the home page in mobile view
And click on the mobile menu
Then the menu shall expand as same as in nowprocket

Scenario3: Should links be clickable While Delay JS is enabled
Given Delay JS is enabled
And Separate mobile cache is enabled
When theme 'x' is activated
And visit the home page in mobile view
And click on the link in the page
Then the page navigated to the new page

Scenario4: Shouldn't cause console error when enabling Delay JS with WPML
Given WPML is active as 'setup-type'
And Delay JS is enabled
When visiting the test page 
And switch language 
Then no console error different than nowprocket page

**Additional context**
- Themes to be checked: Divi, Astra, Avada, Flatsome, Genesis, Bridge, Uncode, Kadence, Neve
- Todo=> For point 5, check what other tests are doable to automate 
- Todo=> For 4 Check old issues to gather needed plugins to test and if we need any VR 
- For WPML , we need to check the different setup (perhaps this can be in WPML suite instead)

**Comment by jeawhanlee** [comment]
### Scope a solution ✅
- Firstly, we need to install the stated themes outlined above on our e2e dedicated test site.
- Create new feature to hold gherkin step above
- Create a new step definition to handle theme switching in [general](https://github.com/wp-media/wp-rocket-e2e/blob/trunk/src/support/steps/general.ts)
To check for console error different than nowprocket page, We can re-use the step definition [here](https://github.com/wp-media/wp-rocket-e2e/blob/29552126306e6552e435e14e762d507dcd6424b8/src/support/steps/general.ts#L189)

Then to adjust viewport size for mobile at run-time we can create a new scenario in [config](https://github.com/wp-media/wp-rocket-e2e/blob/29552126306e6552e435e14e762d507dcd6424b8/config/wp.config.sample.ts#L58) and modify this [function](https://github.com/wp-media/wp-rocket-e2e/blob/29552126306e6552e435e14e762d507dcd6424b8/utils/helpers.ts#L232) to allow for addition of `viewports` option for that specific scenario.

We will also create a new onReadyScript [here](https://github.com/wp-media/wp-rocket-e2e/tree/trunk/backstop_data/engine_scripts) for this scenario to click the collapsible nav menu as the test demands.

Finally for each of our scenario that asserts this: `Then no console error different than nowprocket page` we will change that step to something like this: https://github.com/wp-media/wp-rocket-e2e/blob/29552126306e6552e435e14e762d507dcd6424b8/src/features/ll-css-bg-image-fallback-js-disabled.feature#L10 but instead of noJsLlcss we use the new label of the `SCENARIO_URLS` we added in our config

### Estimate the effort ✅
[S]
