### ISSUE TITLE
Migrate hardcoded tests to cucumber

### ISSUE THREAD

**Issue by MathieuLamiot** [wp-media/wp-rocket-e2e#5]
Sub-task of https://github.com/wp-media/wp-rocket-e2e/issues/1

Context

The wp-rocket-e2e project has a great potential to speed up our development processes: as suggested by @CrochetFeve0251 in https://github.com/wp-media/wp-rocket-e2e/issues/1, every developer could leverage it to automate testing and validation of acceptance criteria. This means that many people will perform small updates regularly on this repository. However, it is currently not up to standards, making it difficult to maintain properly overtime.

Several steps must be taken to make this codebase "production ready".

Issue

Some tests implemented before adding Cucumber support to the project are still "hardcoded" in TS. They must all be migrated to Cucumber.

Note: this will allow to enrich the set of cucumber instructions.

**Comment by jeawhanlee** [comment]
### Scope a solution ✅
Tests are currently executed using playwright test runner, Since cucumber will serve as a layer/runner for our tests, we need to decouple the test logic we have now and the playwright test runner.
All tests that resembles the one below needs to be refactored as we would stop using PW test runner
https://github.com/wp-media/wp-rocket-e2e/blob/38caf2e421cbe0d28e7b80300e2b7f01a78b8f39/src/smoke/roll.back.spec.ts#L10-L16

They will now be wrapped around by the cucumber step definition functions. We will also remove our custom fixture we defined in the [refactor branch](https://github.com/wp-media/wp-rocket-e2e/tree/enhancement/3-refactor) supported by playwright:https://github.com/wp-media/wp-rocket-e2e/blob/enhancement/3-refactor/src/common/fixtures.ts as we will no longer use the Playwright test runner. 

Now the fixture is gone, we need to find a way to share the page object along side our sections and utils object across our steps.
To do that, we will need to create a custom World class and interface that extends the Base World class of cucumber that implements the new interface.

```
import { IWorldOptions, World, setWorldConstructor } from '@cucumber/cucumber'
import { BrowserContext, Page } from '@playwright/test'

export interface ICustomWorld extends World {
	context?: BrowserContext
	page?: Page
}

export class CustomWorld extends World implements ICustomWorld {
	constructor(options: IWorldOptions) {
		super(options)
	}
}

setWorldConstructor(CustomWorld)
```

Then we can use in the step definition like so:

```
When('', function(this: ICustomWorld) {
  const page = this.page!
  await page.goto('some url')
})
```
We also refactor our hooks [here](https://github.com/wp-media/wp-rocket-e2e/blob/enhancement/1-cucumber/features/support/hooks.ts) to implement this new design.

We can also safely delete our [playwright config](https://github.com/wp-media/wp-rocket-e2e/blob/trunk/playwright.config.ts) as it won't be needed anymore.

In this [branch](https://github.com/wp-media/wp-rocket-e2e/tree/enhancement/1-cucumber), we should also separate our features from our step definitions and hooks; We can extract the hooks and step definitions from the features folder and both can co-exist in the same directory but the features should stand-alone holding all features file.

Then we will create general step definitions that can be used by various features.
like navigations and logins and section options toggling.

As discussed with @MathieuLamiot We will start migrating all our hardcoded smoke tests in PW to cucumber.

### Estimate the effort ✅
[L]
