### ISSUE TITLE
Resolve flaky LCP test for Desktop & Mobile

### ISSUE THREAD

**Issue by jeawhanlee** [wp-media/wp-rocket-e2e#97]
**Is your feature request related to a problem? Please describe.**
We sometimes have expectations failing for some templates commonly among these:
- lcp_img_loadedbydynamicjs_template
- lcp_rsponsive_imagegrid
- lcp_no_dimension_absolute_url
There is a detailed link to this here: https://wp-media.slack.com/archives/CUT7FLHF1/p1717582613603429?thread_ts=1717511097.881919&cid=CUT7FLHF1

**Describe the solution you'd like**
We should resolve and identify the cause of this flaky behaviour for these templates.

**Describe alternatives you've considered**

**Additional context**
It's observed that this is common among templates that have external hosts in their expected LCP/ATF candidates, this could be because of network latency, if this is the case, @wp-media/qa-team could try to limit these candidates to our local domain.

**Comment by MathieuLamiot** [comment]
To begin with, we must flag the following tests so that they don't run for the specified device type. Warning: if we disable a test for mobile, it must not be disabled for desktop! And the other way around too.

Desktop:
- lcp_img_loadedbydynamicjs_template (Reason: Flaky with external host)
- lcp_rsponsive_imagegrid (Reason: Flaky with external host)
- lcp_no_dimension_absolute_url (Reason: Flaky with external host)

Mobile:
- lcp_bg_samestyle_template (Reason: wrong expected results)
- lcp_img_loadedbydynamicjs_template (Reason: Flaky with external host)
- lcp_img_loadedbyjs_template (Reason: wrong expected results)
- lcp_bg_multimage_template (Reason: wrong expected results)
- lcp_bg_responsive_webkit_template (Reason: wrong expected results)
- lcp_rsponsive_imagegrid (Reason: Flaky with external host)
- lcp_attribute_template (Reason: wrong expected results)
- lcp_no_dimension_absolute_url (Reason: Flaky with external host)
